services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.11.3
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
      - http.cors.enabled=true
      - http.cors.allow-origin=http://localhost:8081
      - http.cors.allow-headers=X-Requested-With,Content-Type,Content-Length,Authorization
    ports:
      - "9200:9200"
    volumes:
      - esdata:/usr/share/elasticsearch/data

  ocr_service:
    build: ocr_service
    container_name: ocr-worker
    depends_on:
      - elasticsearch
    volumes:
      - ./documents:/documents
    environment:
      - ELASTICSEARCH_HOST=http://elasticsearch:9200

  api_service:
    build: ./api_service
    container_name: ocr-search-api
    depends_on:
      - elasticsearch
    ports:
      - "8000:8000"
    environment:
      - ELASTICSEARCH_HOST=http://elasticsearch:9200

  web:
    image: nginx:alpine
    container_name: ocr-web
    ports:
      - "8080:80"
    volumes:
      - ./web:/usr/share/nginx/html:ro

  elasticvue:
    image: cars10/elasticvue
    container_name: elasticvue
    ports:
      - "8081:8080"
    depends_on:
      - elasticsearch

volumes:
  esdata:
